version: '3'
services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'

  frontend:
    build: ./frontend
    ports:
      - '8080:8080'

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: tododb
    ports:
      - '5432:5432'